Fix broken links in README.md
47deg/freestyle pull request #180
Opened 2017-04-04 17:10 UTC by suhasgaddam

Fixes #179

2017-04-05 12:32 UTC, diesalbla commented
@suhasgaddam When I look at the docs in the present `master`, be it either locally or in the [web page](http://frees.io/), those links are not broken.

Note that, the way the `jekyll` or the `sbt-microsites` work, each file like `algebras.md` and `modules.md` has a permalink definition at the top. Thus, any link in the site that goes to that permalink, will be redirected to the file.

2017-04-05 15:04 UTC, suhasgaddam commented
@diesalbla 

It looks like there are 2 `README.md` files.
* https://github.com/47deg/freestyle/blob/master/docs/src/main/tut/README.md
  * I am guessing this is the source for sbt-microsites/jekyll
  * This page seems broken in GitHub's Markdown viewer
* https://github.com/47deg/freestyle/blob/master/README.md
  * This one has broken links through GitHub's Markdown viewer
  * I edited this file at the root of the repo which I don't think it is compiled with sbt-microsites/jekyll
  * Also, this file looks very similar to the other `README.md`

2017-04-05 15:14 UTC, diesalbla commented
@raulraja On what @suhasgaddam comments: ¿should the `README.md` at the root folder contain exactly the same as the `docs`? ¿Or should it rather be focused on how to use-integrate-build-test the library itself?

2017-04-06 13:59 UTC, raulraja commented
@diesalbla the README in docs/ is the one for the [frees.io](http://frees.io) site and the one at the root is the one for github. Eventually the one in github will have different content and they should not be the same.
The links of both the docs and github should work when navigating inside the docs/ folder whether that happens in github or in the site. That is why all files should be `docs/section/README.md` so github automatically displays the proper docs as niavigating through folders. Currently a few of those are broken because they are not `README` files inside a folder.

2017-04-08 13:39 UTC, raulraja commented
What we can do in this PR or another to get this solved is ensure all docs files conform to the following structure: `docs/section/README.md` This will make it work both in github and the doc site provided that permalinks as defined in the Jekyll site looks like `docs/section` without the `README` piece. @suhasgaddam if you want to give it a shot we can get everything fixed for all docs both on github and the frees.io site. 

An example of a currently working link that works both on github and jekyll is : https://github.com/47deg/freestyle/tree/master/docs/src/main/tut/docs/fetch 

If you notice by navigating to that folder Github automatically displays the README file.
Since Jekyll allows us to customize permalinks, we set the permalink in that doc to `/docs/fetch` and jekyll also shows the README file.

If we apply this same technique to the rest of files we will have the best of both worlds.

2017-04-10 17:30 UTC, suhasgaddam commented
Directories that need `README.md`
* https://github.com/47deg/freestyle/tree/master/docs/src/main/tut/docs/core
* https://github.com/47deg/freestyle/tree/master/docs/src/main/tut/docs/http
* https://github.com/47deg/freestyle/tree/master/docs/src/main/tut/docs/integrations
* https://github.com/47deg/freestyle/tree/master/docs/src/main/tut/docs/patterns

Since these are parent topics, does it make sense to have a simple `README.md` with links/navigation to the children markdown files?

2017-04-11 10:03 UTC, raulraja commented
They all really need to be README including children AFAIK, otherwise navigating to child nodes won't work on github because github expects the files to actually be called README to display them when navigating to a folder view.

2017-04-11 18:27 UTC, suhasgaddam commented
Well, I fixed all the links for GitHub which then broke all the links for sbt-microsite/jekyll...

2017-04-11 23:54 UTC, raulraja commented
Maybe the permalinks in the menu and each file header needs to be adjusted?

On Tue, Apr 11, 2017, 7:27 PM Suhas Gaddam <notifications@github.com> wrote:

> Well, I fixed all the links for GitHub which then broke all the links for
> sbt-microsite/jekyll...
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/47deg/freestyle/pull/180#issuecomment-293356969>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAb4XFoqfpP8Ss2lOIFS_cgajI6h4I4nks5ru8YIgaJpZM4MzKIa>
> .
>

2017-04-15 21:44 UTC, raulraja requested changes

2017-04-15 21:44 UTC, raulraja commented on README.md
> +Freestyle includes all the implicit machinery necessary to achieve seamless dependency injection of [`@free`](/docs/src/main/tut/docs/core/algebras/) and [`@module`](/docs/src/main/tut/docs/core/modu
These links should point to the actual urls at http://frees.io

2017-04-15 21:44 UTC, raulraja commented on docs/src/main/tut/README.md
> +Freestyle includes all the implicit machinery necessary to achieve seamless dependency injection of [`@free`](/docs/src/main/tut/docs/core/algebras) and [`@module`](/docs/src/main/tut/docs/core/modul
These are internal links in frees.io also. To get them to work in github and inside frees.io we may just use the absolute urls in frees.io to whatever content they are pointing to.

2017-04-18 17:14 UTC, raulraja approved these changes

2017-04-18 17:14 UTC, merged